### ISSUE TITLE
Can you write a call flow?

### ISSUE THREAD

**Issue by 107295472** [NikiforovAll/flowable-sdk-dotnet#1]
1. Definition
2. Deployment
3. Run

**Comment by 107295472** [comment]
The HTTP status code of the response was not expected (401).\n\nStatus: 401\nResponse: \n{\"timestamp\":\"2022-06-24T03:51:36.336+00:00\",\"status\":401,\"error\":\"Unauthorized\",\"path\":\"/flowable-ui/process-api/management/engine\


 public string BaseUrlProcessApi { get; set; } = "http://rest-admin:test@192.168.10.21:8083/flowable-ui/process-api/";

**Comment by NikiforovAll** [comment]
Are you sure that flowable expects basic authentication? I guess that you need to authenticate diffrently. Usually, it is a bearer token, so in order to make it work you need to set up `DelegatingHandler` luckily, there is an open-source project that helps with that:
https://identitymodel.readthedocs.io/en/latest/aspnetcore/web.html

See: .AddClientAccessTokenHandler(); AddAccessTokenManagement();

**Comment by NikiforovAll** [comment]
```csharp

public static IServiceCollection AddFlowableHttpIntegration(
    this IServiceCollection services,
    IConfiguration configuration)
{
    services.AddAccessTokenManagement(options =>
    {
        options.Client.Clients.Add("", <provider depending on your oidc flow>);
    });

    services.AddHttpClient<IFlowableProcessHttpClient, FlowableProcessHttpClient>(
        options => options.BaseAddress = new Uri(flowableConfiguration.BaseUrlProcessApi))
            .AddClientAccessTokenHandler();

    return services;
}
```

**Comment by 107295472** [comment]
thanks

**Comment by 107295472** [comment]
![image](https://user-images.githubusercontent.com/6436116/175817967-5debc067-02eb-4578-99a0-4a87f2ee9b3c.png)

**Comment by 107295472** [comment]
Postman can, using this sdk is 401

**Comment by 107295472** [comment]
Using AddFlowableHttpIntegration, is this AddFlowableHttpClients still used?

**Comment by 107295472** [comment]
public static IServiceCollection AddFlowableHttpIntegration(
            this IServiceCollection services,
            IConfiguration configuration, AppConfig app)
        {
            
            services.AddAccessTokenManagement(options =>
            {
                options.Client.Clients.Add("key_flow", new IdentityModel.Client.ClientCredentialsTokenRequest()
                {
                    Address = "",
                    ClientId = "rest-admin",
                    ClientSecret = "test"
                });
            });

            services.AddHttpClient<IFlowableProcessHttpClient, FlowableProcessHttpClient>(
                options => options.BaseAddress = new Uri(app.FlowConfig.BaseUrlProcessApi))
                    .AddClientAccessTokenHandler();

            return services;
        }

**Comment by 107295472** [comment]
To add header Authorization
Basic cmVzdC1hZG1pbjp0ZXN0

**Comment by 107295472** [comment]
options.DefaultRequestHeaders.Add("Authorization", "Basic cmVzdC1hZG1pbjp0ZXN0");
