### ISSUE TITLE
I have to write a lot of empty parameters after ListTasksAsync.

### ISSUE THREAD

**Issue by 107295472** [NikiforovAll/flowable-sdk-dotnet#2]
Actually pass an assignee

**Comment by 107295472** [comment]
The api can't pass the bpmn20.xml file yet, only the flowable java sdk can be used

**Comment by NikiforovAll** [comment]
The API is automatically generated, we might try to adjust swagger.json file used for generation to support this scenario. Or adjust generated code to work with file. Is it something you would like to do? I'm open for contributions

**Comment by NikiforovAll** [comment]
I haven't tried, but it looks like generated code support something called `FileParameter` have you managed to compose a valid one?

https://csharp.hotexamples.com/examples/-/FileParameter/-/php-fileparameter-class-examples.html
